### ISSUE TITLE
Unable to find chrome_elf.dll program at the prompt in Win7

### ISSUE THREAD

**Issue by colorfulbinary** [jcefmaven/jcefmaven#100]
Describe the bug
Unable to find chrome_elf.dll program at the prompt in Win7，Win10 can run normally

To Reproduce

CefApp.getInstance(args,settings)
Expected behavior

Screenshots
图片

Environment (please complete the following information):

OS: windows 7 sp1
Architecture: amd64
Version cef_binary_116.0.19+ge452d82+chromium-113.0.5672.93_windows64

**Comment by wuhuagang** [comment]
windows 7 only support chrome version <= 109, your version is too high

**Comment by FriwiDev** [comment]
It might be that this is indeed a support issue in chrome. Using chrome below version 116 is not recommended though, due to various exploits that have recently been fixed. Windows 7 is also end of life since 2020, so supporting it does not really make sense for this library. I will thus close this issue for now, unless there is an easy fix for this.
