### ISSUE TITLE
cookiemanager

### ISSUE THREAD

**Issue by jh2310** [jcefmaven/jcefmaven#59]
Hello, I listened to your suggestion the other day to use cookiemanager, but I passed a cefrequestcontext object to createbrowser, which has a cefrequestcontexthadler object. This object has a method that can get the cookiemanager, and then I used the method I created. However, when I call it, I will not call this custom cookiemanager. What is the possible reason, I'd appreciate it if you could help me with the answer

**Comment by FriwiDev** [comment]
I would assume that the cookiemanager doesnt actually get called from cef, but the cookiemanager calls cef. This means that you probably cant alter the implementation of the cookiemanager. You can however delete and add back cookies how you wish. So you could potentially swap cookies before you create a new request in another window. If you want to discuss with other users of this library I'd recommend using the discussion section instead of the issues for the future, or use the jcef forum (linked to by the main jcef project - give it a try). :)

**Comment by FriwiDev** [comment]
Some more info on this: https://www.magpcss.org/ceforum/viewtopic.php?t=17334
