### ISSUE TITLE
Upgrade artifact version and to lastest CEF version

### ISSUE THREAD

**Issue by Sage-Kreiter** [jcefmaven/jcefmaven#98]
**Is your feature request related to a problem? Please describe.**
The current artifact version is JCEF 116, but in the `jcefbuild` project, the latest build version is JCEF 119. Is there a reason for this not being updated? Additionally, the latest version of java-cef is 121, so is there a reason to not be up to date with that version as well?

**Describe the solution you'd like**
Upgrade the artifact versions if possible

**Comment by FriwiDev** [comment]
The current blocker on this is the apple notarization staple action failing because of an invalid bundle structure. I will be working on a fix for this in the upcoming weeks, but for now new releases would need to be published without macos support. This is why I published a partial build for jcefbuild, but not for jcefmaven.

**Comment by Sage-Kreiter** [comment]
Got it. I didn't notice they were partial builds. Thanks for the update!

**Comment by FriwiDev** [comment]
Now updated to 122.1.10 :)

**Comment by Sage-Kreiter** [comment]
Awesome! Thanks for maintaining this!
